export const TEST_DISPATCH = 'TEST_DISPATCH';
export const GET_ERRORS = 'GET_ERRORS';
export const TOURNAMENT_LOADING = 'TOURNAMENT_LOADING';
export const TOURNAMENT_NOT_FOUND = 'TOURNAMENT_NOT_FOUND';
export const GET_TOURNAMENT = 'GET_TOURNAMENT';
